version: 2
updates:
  # New major versions of the base image (minor and patch versions are used
  # automatically, because the Dockerfile uses the major version tag)
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "feat(devcontainer)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
